backend:
  name: git-gateway
  branch: main 
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "properties"
    label: "Property"
    folder: "properties"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Area", name: "area", widget: "string"}
      - {label: "Specs", name: "specs", widget: "string"}
      - {label: "Features", name: "features", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}